[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["daniel <daniel.battaglia@navitus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"